### ISSUE TITLE
Add the source code to git

### ISSUE THREAD

**Issue by tushar9989** [kevinpat5/BiggerDigger#1]

**Comment by tushar9989** [comment]
No comments? Just a scam then?

**Comment by kevinpat5** [comment]
Sorry for the delay, i was too occupied.
No my friend, its not a scam at all.
But i hadn't any comments since i fully covered the subject in the readme.
BiggerDigger is 100% clean.

________________________________
Από: tushar9989 <notifications@github.com>
Στάλθηκε: Κυριακή, 18 Φεβρουαρίου 2018 8:21 μμ
Προς: kevinpat5/BiggerDigger
Κοιν.: kevinpat5; State change
Θέμα: Re: [kevinpat5/BiggerDigger] Add the source code to git (#1)


No comments? Just a scam then?

**Comment by tushar9989** [comment]
If it is not a scam, why not put the source code on git so we can verify.
